
#~~~~~~~~~~~~~~~~IMAGE CONSTANTS~~~~~~~~~~~~~~~#

IMAGE_STATUS_PENDING = 0
IMAGE_STATUS_DOWNLOAD_FAILED = 1
IMAGE_STATUS_DOWNLOAD_SUCCESS = 2

IMAGE_STATUS_CHOICES = (
    (IMAGE_STATUS_PENDING, "Pending"),
    (IMAGE_STATUS_DOWNLOAD_FAILED, "Download failed"),
    (IMAGE_STATUS_DOWNLOAD_SUCCESS, "Download success"),
)

API_KEYWORD_TYPE_CATEGORY = 'category'
API_KEYWORD_TYPE_FAVORITE = 'favorite'
API_KEYWORD_TYPE_READ_MOST = 'read-most'
API_KEYWORD_TYPE_NEW = 'new'
API_KEYWORD_TYPE_SEARCH = 'search'
API_KEYWORD_SEARCH_TYPE_AUTHOR = 'author'
API_KEYWORD_SEARCH_TYPE_EBOOK = 'ebook_name'

API_LIMIT_ELEMENT_SEARCH = 10