
#~~~~~~~~~~~~~~~~IMAGE CONSTANTS~~~~~~~~~~~~~~~#

IMAGE_STATUS_PENDING = 0
IMAGE_STATUS_DOWNLOAD_FAILED = 1
IMAGE_STATUS_DOWNLOAD_SUCCESS = 2

IMAGE_STATUS_CHOICES = (
    (IMAGE_STATUS_PENDING, "Pending"),
    (IMAGE_STATUS_DOWNLOAD_FAILED, "Download failed"),
    (IMAGE_STATUS_DOWNLOAD_SUCCESS, "Download success"),
)

